name = "cloudflare-workers-crud"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-04-04"

[build]
command = "npm run build"
[build.upload]
format = "service-worker"

